name: GikyMessage build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    - name: Checkout GikyMessage
      uses: actions/checkout@v4
      with:
        repository: groundbreakingmc/GikyMessage
        path: giky-message-src

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Check Cache for GikyMessage Repository
      id: cache-lib
      uses: actions/cache@v4
      with:
        path: lib/com/github/groundbreakingmc/GikyMessage
        key: giky-repo-${{ hashFiles('giky-message-src/settings.gradle.kts', 'giky-message-src/build.gradle.kts') }}

    - name: Publish GikyMessage to Maven Local
      if: steps.cache-lib.outputs.cache-hit != 'true'
      run: |
        cd giky-message-src
        chmod +x gradlew
        ./gradlew publishToMavenLocal

    - name: Copy Maven Local repository to lib
      if: steps.cache-lib.outputs.cache-hit != 'true'
      run: |
        mkdir -p lib/com/github/groundbreakingmc
        rm -rf lib/com/github/groundbreakingmc/GikyMessage
        cp -r /home/runner/.m2/repository/com/github/groundbreakingmc/GikyMessage lib/com/github/groundbreakingmc/

    - name: Push Maven Local repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: автоматическое обновление GikyMessage [skip ci]"
        file_pattern: 'lib/**'
        branch: ${{ github.ref_name }}
        skip_fetch: false

    - name: Update lib folder
      run: |
        mkdir -p /home/runner/.m2/repository/com/github/groundbreakingmc
        cp -r lib/com/github/groundbreakingmc/GikyMessage /home/runner/.m2/repository/com/github/groundbreakingmc/

    - name: Build plugin
      run: mvn clean package --batch-mode

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RPplugin
        path: target/RPplugin-*.jar
